let EmployeeActionTypes = {
    GET_EMPLOYEES_LOAD: "GET_EMPLOYEES_LOAD",
    GET_EMPLOYEES_SUCC: "GET_EMPLOYEES_SUCC",
    GET_EMPLOYEES_FAIL: "GET_EMPLOYEES_FAIL",

    ADD_EMPLOYEE_LOAD:"ADD_EMPLOYEE_LOAD",
    ADD_EMPLOYEE_SUCC:"ADD_EMPLOYEE_SUCC",
    ADD_EMPLOYEE_FAIL:"ADD_EMPLOYEE_FAIL",

    UPDATE_EMPLOYEE_LOAD:"UPDATE_EMPLOYEE_LOAD",
    UPDATE_EMPLOYEE_SUCC:"UPDATE_EMPLOYEE_SUCC",
    UPDATE_EMPLOYEE_FAIL:"UPDATE_EMPLOYEE_FAIL",

    DELETE_EMPLOYEE_LOAD:"DELETE_EMPLOYEE_LOAD",
    DELETE_EMPLOYEE_SUCC:"DELETE_EMPLOYEE_SUCC",
    DELETE_EMPLOYEE_FAIL:"DELETE_EMPLOYEE_FAIL",

    CLEAR_EMPLOYEE_SUCC:"CLEAR_EMPLOYEE_SUCC"
}
export default EmployeeActionTypes;

